#
# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicasle law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import("../../iotc.gni")

iotc_core_sle_inc = [
  "$iotc_core_path/sle/interfaces/include",
  "$iotc_core_path/sle/infrastructure/stack/adv/include",
  "$iotc_core_path/sle/infrastructure/stack/disc/include",
  "$iotc_core_path/sle/infrastructure/stack/conn/include",
  "$iotc_core_path/sle/infrastructure/stack/ssap/include",
  "$iotc_core_path/sle/infrastructure/stack/ssap",
  "$iotc_core_path/sle/infrastructure/utils/include",
  "$iotc_core_path/sle/application/base/include",
  "$iotc_core_path/sle/application/ssap/include",
  "$iotc_core_path/sle/application/profile",
  "$iotc_core_path/sle/application/profile/include",
  "$iotc_core_path/sle/application/profile",
  "$iotc_core_path/sle/application/report/include",
  "$iotc_core_path/sle/application/include",
  "$iotc_core_path/ble/infrastructure/utils/include",
  "$iotc_core_path/ble/infrastructure/linklayer/include",
  "$iotc_core_path/sle/infrastructure/linklayer",
  "$iotc_core_path/sle/infrastructure/linklayer/include",
  "$iotc_core_path/sle/infrastructure/stack/conn_dev_mgt",
]


iotc_core_sle_src = [
  "$iotc_core_path/sle/interfaces/core_sle_init.c",
  "$iotc_core_path/sle/infrastructure/stack/disc/sle_disc_ctrl.c",
  "$iotc_core_path/sle/infrastructure/stack/disc/sle_disc_event.c",
  "$iotc_core_path/sle/infrastructure/stack/conn/sle_conn_ctrl.c",
  "$iotc_core_path/sle/infrastructure/stack/conn/sle_conn_event.c",
  "$iotc_core_path/sle/infrastructure/stack/ssap/sle_ssap_event.c",
  "$iotc_core_path/sle/infrastructure/stack/ssap/sle_ssap_mgt.c",
  "$iotc_core_path/sle/infrastructure/stack/ssap/sle_sched_event.c",
  "$iotc_core_path/sle/infrastructure/utils/sle_common.c",
  "$iotc_core_path/sle/application/base/sle_session_mngr.c",
  "$iotc_core_path/sle/application/base/sle_speke_session.c",
  "$iotc_core_path/sle/application/ssap/sle_ssap_data_svc.c",
  "$iotc_core_path/sle/application/profile/sle_profile.c",
  "$iotc_core_path/sle/application/profile/sle_svc_auth_setup.c",
  "$iotc_core_path/sle/application/profile/sle_svc_clear_dev_reg_info.c",
  "$iotc_core_path/sle/application/profile/sle_svc_create_session.c",
  "$iotc_core_path/sle/application/profile/sle_svc_custom_sec_data.c",
  "$iotc_core_path/sle/application/profile/sle_svc_device_info.c",
  "$iotc_core_path/sle/application/profile/sle_svc_net_cfg_ver.c",
  "$iotc_core_path/sle/application/profile/sle_svc_netcfg.c",
  "$iotc_core_path/sle/application/profile/sle_svc_speke.c",
  "$iotc_core_path/sle/application/profile/sle_svc_ctx.c",
  "$iotc_core_path/sle/application/report/sle_svc_netcfg_status.c",
  "$iotc_core_path/sle/application/report/sle_svc_report.c",
  "$iotc_core_path/sle/application/sle_svc.c",
  "$iotc_core_path/sle/infrastructure/linklayer/sle_linklayer_encrypt_speke.c",
  "$iotc_core_path/sle/infrastructure/linklayer/sle_linklayer_encrypt_sesskey.c",
  "$iotc_core_path/sle/infrastructure/linklayer/sle_linklayer_encrypt.c",
  "$iotc_core_path/sle/infrastructure/linklayer/sle_linklayer_process.c",
  "$iotc_core_path/sle/infrastructure/linklayer/sle_linklayer_recv.c",
  "$iotc_core_path/sle/infrastructure/linklayer/sle_linklayer_send.c",
  "$iotc_core_path/sle/infrastructure/linklayer/sle_linklayer_service.c",
]


if (defined(ohos_lite))
{
  iotc_core_sle_inc += [
    "$iotc_core_path/sle/application/ssaps/include",
    "$iotc_core_path/sle/application/adv/include",
    "$iotc_core_path/sle/application/ssaps/include",
  ]
  iotc_core_sle_src += [
    "$iotc_core_path/sle/infrastructure/stack/adv/sle_adv_ctrl.c",
    "$iotc_core_path/sle/application/adv/sle_adv_data.c",
    "$iotc_core_path/sle/application/adv/sle_adv_param.c",
    "$iotc_core_path/sle/application/adv/sle_adv.c",
    "$iotc_core_path/sle/application/ssaps/sle_server_event_service.c",
    "$iotc_core_path/sle/infrastructure/stack/ssaps/sle_ssaps_event.c"
  ]
}


if (!defined(ohos_lite)) {
  iotc_core_sle_inc += [
    "$iotc_core_path/sle/infrastructure/stack/ssapc/include",
    "$iotc_core_path/sle/application/ssapc/include",
  ]
  iotc_core_sle_src += [
    "$iotc_core_path/sle/application/ssapc/sle_client_event_service.c",
    "$iotc_core_path/sle/infrastructure/stack/ssapc/sle_ssapc_ctrl.c",
    "$iotc_core_path/sle/infrastructure/stack/ssapc/sle_ssapc_event.c",
    "$iotc_core_path/sle/application/ssapc/sle_client_stubs.c",
    "$iotc_core_path/sle/infrastructure/stack/conn_dev_mgt/sle_conn_mgt.c",
    "$iotc_core_path/sle/infrastructure/stack/ssapc/sle_ssapc_mgt.c"
  ]
}



if(!iot_connect_ble_support){
  #  from BLE
  iotc_core_sle_src += [
    "$iotc_core_path/ble/infrastructure/linklayer/linklayer_encrypt.c",
    "$iotc_core_path/ble/infrastructure/linklayer/linklayer_process.c",
    "$iotc_core_path/ble/infrastructure/linklayer/linklayer_recv.c",
    "$iotc_core_path/ble/infrastructure/linklayer/linklayer_send.c",
    "$iotc_core_path/ble/infrastructure/linklayer/linklayer_service.c",
    "$iotc_core_path/ble/infrastructure/linklayer/linklayer_encrypt_speke.c",
    "$iotc_core_path/ble/infrastructure/linklayer/linklayer_encrypt_sesskey.c",
  ]
}

iotc_core_sle_def = []