#
# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import("../../iotc.gni")

wifi_core_path = "${iotc_root_path}/core/wifi"

iotc_core_wifi_inc = [
  "$wifi_core_path/interfaces/include",
  "$wifi_core_path/application/netcfg/softap/include",
  "$wifi_core_path/application/connect/include",
  "$wifi_core_path/application/netcfg/fsm/include",
  "$wifi_core_path/application/netcfg/info/include",
  "$wifi_core_path/application/netcfg/softap/include",
  "$wifi_core_path/application/cloud/include",
  "$wifi_core_path/application/cloud/link/include",
  "$wifi_core_path/application/cloud/link/sess/include",
  "$wifi_core_path/application/cloud/biz/include",
  "$wifi_core_path/application/cloud/ctx/include",
  "$wifi_core_path/application/softap/include",
  "$wifi_core_path/application/connect/include",
  "$wifi_core_path/application/lan_search/include",
  "$wifi_core_path/application/local_control/include",
  "$wifi_core_path/domain/e2e_ctl/include",
  "$wifi_core_path/infrastructure/define",
  "$wifi_core_path/infrastructure/schedule/include",
  "$wifi_core_path/infrastructure/transport/coap/codec/include",
  "$wifi_core_path/infrastructure/transport/coap/endpoint/include",
  "$wifi_core_path/infrastructure/transport/coap/stack/include",
  "$wifi_core_path/infrastructure/transport/link/include",
  "$wifi_core_path/infrastructure/transport/session/include",
  "$wifi_core_path/infrastructure/transport/socket/include",
  "$wifi_core_path/infrastructure/transport/buffer/include",
  "$wifi_core_path/infrastructure/utils/include",
]

iotc_core_wifi_src = [
  "$wifi_core_path/interfaces/core_wifi_init.c",
  "$wifi_core_path/application/softap/svc_softap_coap.c",
  "$wifi_core_path/application/softap/svc_softap_ctx.c",
  "$wifi_core_path/application/softap/svc_softap_report.c",
  "$wifi_core_path/application/softap/svc_softap_retrans.c",
  "$wifi_core_path/application/softap/svc_softap_sess.c",
  "$wifi_core_path/application/softap/svc_softap_ssid.c",
  "$wifi_core_path/application/softap/wifi_svc_softap.c",
  "$wifi_core_path/application/connect/svc_conn_action.c",
  "$wifi_core_path/application/connect/svc_conn_conf.c",
  "$wifi_core_path/application/connect/svc_conn_ctx.c",
  "$wifi_core_path/application/connect/svc_conn_net_info.c",
  "$wifi_core_path/application/connect/wifi_svc_conn.c",
  "$wifi_core_path/application/lan_search/lan_search_coap_api.c",
  "$wifi_core_path/application/lan_search/lan_search_coap_stack.c",
  "$wifi_core_path/application/lan_search/lan_search_ctx.c",
  "$wifi_core_path/application/lan_search/lan_search_peer_mngr.c",
  "$wifi_core_path/application/lan_search/lan_search_sess.c",
  "$wifi_core_path/application/lan_search/lan_search_svc.c",
  "$wifi_core_path/application/local_control/local_ctl_coap_api.c",
  "$wifi_core_path/application/local_control/local_ctl_coap_stack.c",
  "$wifi_core_path/application/local_control/local_ctl_cli_mngr.c",
  "$wifi_core_path/application/local_control/local_ctl_ctx.c",
  "$wifi_core_path/application/local_control/local_ctl_report.c",
  "$wifi_core_path/application/local_control/local_ctl_sess.c",
  "$wifi_core_path/application/local_control/local_ctl_svc.c",

  "$wifi_core_path/application/cloud/m2m_cloud_backoff.c",
  "$wifi_core_path/application/cloud/m2m_cloud_fsm.c",
  "$wifi_core_path/application/cloud/m2m_cloud_svc.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_login.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_reg.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_send.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_sync.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_token.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_utils.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_heartbeat.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_ctl.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_report.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_dev_del.c",
  "$wifi_core_path/application/cloud/biz/m2m_cloud_revoke.c",
  "$wifi_core_path/application/cloud/ctx/m2m_cloud_ctx.c",
  "$wifi_core_path/application/cloud/link/m2m_cloud_link.c",
  "$wifi_core_path/application/cloud/link/sess/tls/m2m_cloud_sess.c",

  "$wifi_core_path/infrastructure/schedule/wifi_sched_fd_watch.c",
  "$wifi_core_path/infrastructure/transport/coap/codec/coap_codec_comm.c",
  "$wifi_core_path/infrastructure/transport/coap/codec/coap_codec_tcp_v1.c",
  "$wifi_core_path/infrastructure/transport/coap/codec/coap_codec_udp.c",
  "$wifi_core_path/infrastructure/transport/coap/codec/coap_codec_utils.c",
  "$wifi_core_path/infrastructure/transport/coap/endpoint/coap_endpoint.c",
  "$wifi_core_path/infrastructure/transport/coap/endpoint/coap_endpoint_client.c",
  "$wifi_core_path/infrastructure/transport/coap/endpoint/coap_endpoint_server.c",
  "$wifi_core_path/infrastructure/transport/coap/endpoint/coap_endpoint_retrans.c",
  "$wifi_core_path/infrastructure/transport/coap/endpoint/coap_endpoint_event_source.c",
  "$wifi_core_path/infrastructure/transport/coap/stack/coap_net_stack.c",
  "$wifi_core_path/infrastructure/transport/link/trans_link.c",
  "$wifi_core_path/infrastructure/transport/session/trans_sess.c",
  "$wifi_core_path/infrastructure/transport/socket/trans_socket.c",
  "$wifi_core_path/infrastructure/transport/socket/trans_socket_tls.c",
  "$wifi_core_path/infrastructure/transport/socket/trans_socket_udp.c",
  "$wifi_core_path/infrastructure/transport/buffer/trans_buffer_inner.c",
  "$wifi_core_path/domain/e2e_ctl/e2e_ctl_msg.c",
  "$wifi_core_path/infrastructure/utils/wifi_net_info.c",
  "$wifi_core_path/infrastructure/utils/seq_num_utils.c",
]

iotc_core_wifi_def = []