#
# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import("../../../iotc.gni")

if (defined(ohos_lite)) {
  import("//build/lite/config/component/lite_component.gni")
} else {
  import("//build/test.gni")
  module_output_path = "iotc/xts/acts"

  ohos_unittest("IotcOhSdkActsTest") {
    module_out_path = module_output_path
    sources = [ "iotc_oh_sdk_acts_test.cpp" ]
    include_dirs = [
      "$iotc_interface_path/kits/common",
      "$iotc_interface_path/kits/oh_connect",
      "$iotc_core_path/core/infrastructure/utils/include",
    ]
    deps = [
      "../../..:iotc_shared",
    ]
    external_deps = [
      "bounds_checking_function:libsec_static",
      "cJSON:cjson",
      "googletest:gtest_main",
      "c_utils:utils",
      "hilog:libhilog",
    ]
  }

  ohos_unittest("IotcOhBleActsTest") {
    module_out_path = module_output_path
    sources = [ "iotc_oh_ble_acts_test.cpp" ]
    include_dirs = [
      "$iotc_interface_path/kits/common",
      "$iotc_interface_path/kits/oh_connect",
    ]
    deps = [
      "../../..:iotc_shared",
    ]
    external_deps = [
      "bounds_checking_function:libsec_static",
      "cJSON:cjson",
      "googletest:gtest_main",
      "c_utils:utils",
      "hilog:libhilog",
    ]
  }

  ohos_unittest("IotcOhWifiActsTest") {
    module_out_path = module_output_path
    sources = [ "iotc_oh_wifi_acts_test.cpp" ]
    include_dirs = [
      "$iotc_interface_path/kits/common",
      "$iotc_interface_path/kits/oh_connect",
    ]
    deps = [
      "../../..:iotc_shared",
    ]
    external_deps = [
      "bounds_checking_function:libsec_static",
      "cJSON:cjson",
      "googletest:gtest_main",
      "c_utils:utils",
      "hilog:libhilog",
    ]
  }

  ohos_unittest("IotcOhDeviceActsTest") {
    module_out_path = module_output_path
    sources = [ "iotc_oh_device_acts_test.cpp" ]
    include_dirs = [
      "$iotc_interface_path/kits/common",
      "$iotc_interface_path/kits/oh_connect",
    ]
    deps = [
      "../../..:iotc_shared",
    ]
    external_deps = [
      "bounds_checking_function:libsec_static",
      "cJSON:cjson",
      "googletest:gtest_main",
      "c_utils:utils",
      "hilog:libhilog",
    ]
  }

  group("acts") {
    testonly = true
    deps = [
      ":IotcOhSdkActsTest",
      ":IotcOhBleActsTest",
      ":IotcOhWifiActsTest",
      ":IotcOhDeviceActsTest",
    ]
  }
}