#
# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import("../iotc.gni")
import("wifi/core_wifi.gni")
import("infrastructure/core_inf.gni")
import("device/core_dev.gni")
import("ble/core_ble.gni")
import("sle/core_sle.gni")

iotc_core_src = iotc_core_infrastructure_src + iotc_core_device_src
iotc_core_inc = iotc_core_infrastructure_inc + iotc_core_device_inc
iotc_core_def = iotc_core_infrastructure_def + iotc_core_device_def

if (iot_connect_feature_ble_support) {
  iotc_core_inc += iotc_core_ble_inc
  iotc_core_src += iotc_core_ble_src
  iotc_core_def += iotc_core_ble_def
}

if(iot_connect_feature_sle_support) {
  iotc_core_inc += iotc_core_sle_inc
  iotc_core_src += iotc_core_sle_src
  iotc_core_def += iotc_core_sle_def
}

if (iot_connect_feature_wifi_support) {
  iotc_core_inc += iotc_core_wifi_inc
  iotc_core_src += iotc_core_wifi_src
  iotc_core_def += iotc_core_wifi_def
}